@Communication_HostAddress = http://localhost:8080

POST http://localhost:8080/messenger/user
Accept: application/json

{
    "username" : "петя"
}
###

DELETE http://localhost:8080/messenger/user
Accept: application/json

###

GET http://localhost:8080/messenger/chats/all
Accept: application/json
